version: "3.7"
services:
  app:
    build: .
    image: jasonblanchard/jawn-workspace-api
    command:
      - /bin/bash
      - -c
      - |
        npm run start --production
    environment:
      DB_NAME: jawn_test
      MONGO_HOST: mongo
      PORT: '8080'
      LOG_LEVEL: 'DEBUG'
      JWT_SECRET: '$$2a$$10$$HuxYWte8dvZJM9UHBMEFZO'
    container_name: jawn-workspace-api
    depends_on:
      - mongo
    expose:
      - "8080"
    healthcheck:
      test: ["CMD-SHELL", "curl -f app:8080/health || exit 1"]
      interval: 15s
      timeout: 5s
      retries: 3
      start_period: 15s
    networks:
      - default
  tests:
    build:
      context: .
      dockerfile: Dockerfile
      target: test
    image: jasonblanchard/jawn-workspace-api:test
    command:
      - /bin/bash
      - -c
      - |
        tail -f /dev/null
    environment:
      SERVICE_BASE_URL: "http://app:8080"
      JWT_SECRET: '$$2a$$10$$HuxYWte8dvZJM9UHBMEFZO'
    container_name: jawn-workspace-api-test
    networks:
      - default
  mongo:
    image: mongo:3.7.1
    networks:
      - default
networks:
  default:


# version: "3"
# services:
#   app:
#     build: .
#     image: jasonblanchard/jawn-workspace-api
#     expose:
#       - '80'
#     networks:
#       - backend
#     environment:
#       DB_NAME: jawn_test
#       MONGO_HOST: mongo
#       PORT: '8081'
#       LOG_LEVEL: 'DEBUG'
#       APP_SECRET: "$$2a$$10$$HuxYWte8dvZJM9UHBMEFZO" # TODO: Centralize this
#     depends_on:
#       - mongo
#   mongo:
#     image: mongo:3.7.1
#     networks:
#       - backend
# networks:
#   backend:
