apiVersion: v1
kind: Service
metadata:
  name: workspace-mongo
spec:
  type: ClusterIP
  ports:
  - port: 27017
    name: workspace-mongo
  selector:
    app: workspace-mongo
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: workspace-mongo
spec:
  serviceName: workspace-mongo
  replicas: 1
  selector:
    matchLabels:
      app: workspace-mongo
  template:
    metadata:
      labels:
        app: workspace-mongo
    spec:
      containers:
      - name: workspace-mongo
        image: mongo:3.7.1
        ports:
        - containerPort: 27017
        volumeMounts:
          - name: jawn-workspace-api
            mountPath: /data/db
  volumeClaimTemplates:
    - metadata:
        name: jawn-workspace-api
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 1G
